// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoyq57mEbtJaszv9K7H4bk30zRCHjyWJs',
    appId: '1:627206884619:web:0e27f7b4c4de299793660e',
    messagingSenderId: '627206884619',
    projectId: 'routine-mate-a07cd',
    authDomain: 'routine-mate-a07cd.firebaseapp.com',
    storageBucket: 'routine-mate-a07cd.firebasestorage.app',
    measurementId: 'G-HPWKSG5GQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPjnRqbGN3JLGPZ_wHWLrR0YKKnHdj8g',
    appId: '1:627206884619:android:74e1b1b9479d6f0593660e',
    messagingSenderId: '627206884619',
    projectId: 'routine-mate-a07cd',
    storageBucket: 'routine-mate-a07cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqpqaENILBoekh5XV0LphiOBCZJr21eY',
    appId: '1:627206884619:ios:12fc3fe0672a0c6193660e',
    messagingSenderId: '627206884619',
    projectId: 'routine-mate-a07cd',
    storageBucket: 'routine-mate-a07cd.firebasestorage.app',
    iosBundleId: 'com.example.routineMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqpqaENILBoekh5XV0LphiOBCZJr21eY',
    appId: '1:627206884619:ios:12fc3fe0672a0c6193660e',
    messagingSenderId: '627206884619',
    projectId: 'routine-mate-a07cd',
    storageBucket: 'routine-mate-a07cd.firebasestorage.app',
    iosBundleId: 'com.example.routineMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoyq57mEbtJaszv9K7H4bk30zRCHjyWJs',
    appId: '1:627206884619:web:c1756d359230efbd93660e',
    messagingSenderId: '627206884619',
    projectId: 'routine-mate-a07cd',
    authDomain: 'routine-mate-a07cd.firebaseapp.com',
    storageBucket: 'routine-mate-a07cd.firebasestorage.app',
    measurementId: 'G-5V8QNTECVH',
  );
}
